#!/bin/bash
count=0 count=$(find . -type d -mindepth 1 -maxdepth 1 -name ".*" -o -name "*" | wc -l) echo "Total directories and subdirectories (including hidden ones) in the current directory: $count"
